name = Cyber Rasta

ghostty = dark
wezterm = Dark
gtk     = Orchis-Green-Dark
icons   = Colloid-Green-Dark

wallpaper = rasta_3.jpeg

dunst_frame_global       = #00e676

dunst_bg_low             = #0c0c0e
dunst_fg_low             = #e0e0e0
dunst_frame_low          = #4e4e54
dunst_highlight_low      = #00e676

dunst_bg_normal          = #0c0c0e
dunst_fg_normal          = #e0e0e0
dunst_frame_normal       = #00e676
dunst_highlight_normal   = #ffdf00

dunst_bg_critical        = #ff3a3a
dunst_fg_critical        = #e0e0e0
dunst_frame_critical     = #ffdf00
dunst_highlight_critical = #ffdf00
